services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: corneal-ai-backend

    ports:
      - "8080:8080"

    env_file:
      - .env

    environment:
      ML_SERVICE_URL: http://ml-service:8000

    depends_on:
      - ml-service

    restart: unless-stopped

  ml-service:
    build:
      context: ./ml-service
      dockerfile: Dockerfile

    container_name: corneal-ai-ml-service

    ports:
      - "8000:8000"

    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: corneal-ai-frontend

    ports:
      - "3000:80"

    depends_on:
      - backend

    restart: unless-stopped